# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` 

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [4]:
import numpy as np
print("NumPy version:", np.__version__)
print("\nNumPy configuration:")
np.show_config()


NumPy version: 1.26.4

NumPy configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/asc/anaconda3/Library/include
    lib directory: C:/Users/asc/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_

#### 3. Create a null vector of size 10

In [6]:
#import numpy as np
null_vector = np.zeros(10)
print(null_vector)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### 4. How to find the memory size of any array 

In [9]:
array_example = np.array([[1, 2, 3], [4, 5, 6]])
print("Memory size of the array using .nbytes:", array_example.nbytes)


Memory size of the array using .nbytes: 24


In [10]:
array_example = np.array([[1, 2, 3], [4, 5, 6]])
print("Memory size of the array using .size and .itemsize:", array_example.size * array_example.itemsize)


Memory size of the array using .size and .itemsize: 24


#### 5. How to get the documentation of the numpy add function from the command line?

In [13]:
np.info()


 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for an array, function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is
    an `ndarray` instance, information about the array is printed.
    If `object` is a numpy object, its docstring is given. If it is
    a string, available modules are searched for matching objects.
    If None, information about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPyth

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [14]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49

In [15]:
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last)

In [18]:

vector = np.arange(10, 50)
reversed_vector = np.flip(vector)
print("Original Vector:",vector)
print("reversed_vector:",reversed_vector)


Original Vector: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
reversed_vector: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [23]:
import numpy as np
matrix = np.arange(0, 9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [27]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)[0]
print(non_zero_indices)
import numpy as np



[0 1 4]


#### 11. Create a 3x3 identity matrix

In [32]:

array_3x3 = np.ones((3,3))
print(array_3x3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 12. Create a 3x3x3 array with random values

In [36]:
array_3d = np.random.rand(3, 3, 3)
print(array_3d)


[[[0.63895254 0.37570535 0.9202053 ]
  [0.11490671 0.39933383 0.46233343]
  [0.18957439 0.7558866  0.0357208 ]]

 [[0.99447561 0.72446239 0.58018339]
  [0.2000492  0.19494703 0.51041919]
  [0.42798528 0.98934329 0.9559518 ]]

 [[0.9380419  0.26044416 0.85987853]
  [0.66333864 0.73949337 0.90758011]
  [0.68290348 0.3452321  0.99451861]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [43]:

array = np.random.rand(10,10)
print("Array:",array)
v=np.min(array_3d)
print("Min:",v)
v=np.max(array_3d)
print("Max:",v)

Array: [[0.13882457 0.82525291 0.88385282 0.53169136 0.65698207 0.32831541
  0.73863939 0.17833454 0.66632504 0.35148217]
 [0.10655429 0.55664105 0.97136754 0.42349223 0.2357977  0.01769389
  0.17995357 0.76758101 0.57363099 0.3286598 ]
 [0.62994549 0.22878787 0.38881842 0.78992262 0.69800348 0.61848183
  0.80293786 0.95992103 0.74015871 0.02654597]
 [0.07192812 0.57975137 0.05803108 0.63878019 0.4527083  0.56974355
  0.30986322 0.33680097 0.44969517 0.50504963]
 [0.80565915 0.48542732 0.93022468 0.65930262 0.98704971 0.36604031
  0.32681224 0.06848028 0.89237329 0.55880637]
 [0.65623524 0.61279431 0.91740593 0.08763374 0.84003788 0.59013225
  0.92075812 0.36874108 0.73654501 0.91113386]
 [0.70014691 0.52374141 0.98766703 0.4529644  0.81651468 0.301814
  0.43898766 0.00644577 0.56400869 0.95312211]
 [0.0869929  0.29280114 0.78259972 0.72247843 0.08158282 0.78066464
  0.41834314 0.21447972 0.99258596 0.86825585]
 [0.01275807 0.43079678 0.97329229 0.61212457 0.21468601 0.85221433
  0.018

#### 14. Create a random vector of size 30 and find the mean value

In [48]:
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)
print("Random Vector:")
print(random_vector)
print("\nMean Value:")
print(mean_value)


[0.16583274 0.42719287 0.36990173 0.38410228 0.16182959 0.55646643
 0.07054681 0.38860046 0.89122349 0.08252096 0.59337582 0.11766142
 0.91841324 0.14538805 0.3154947  0.494819   0.43826901 0.18062768
 0.48876517 0.57180576 0.17196348 0.73018714 0.58683426 0.74607696
 0.5502544  0.08645622 0.46905201 0.01705081 0.47804851 0.98913824]


#### 15. Create a 2d array with 1 on the border and 0 inside

In [49]:
rows = 10
cols = 10
array_2d = np.zeros((rows, cols))
array_2d[0, :] = 1  # Top row
array_2d[:, 0] = 1  # Left column
array_2d[-1, :] = 1  # Bottom row
array_2d[:, -1] = 1  # Right column

print(array_2d)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

#### 16. How to add a border (filled with 0's) around an existing array?

#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

#### 21. Create a checkerboard 8x8 matrix using the tile function

#### 22. Normalize a 5x5 random matrix

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [53]:

"""(a,b)=(b,a)
print(a,b)"""
a=a^b
b=a^b
a=b^a
print(a,b)


8 6


#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ?

#### 30. How to find common values between two arrays?

#### 31. How to ignore all numpy warnings (not recommended)?

#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow?

#### 34. How to get all the dates corresponding to the month of July 2016?

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

#### 38. Consider a generator function that generates 10 integers and use it to build an array

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

#### 40. Create a random vector of size 10 and sort it

#### 41. How to sum a small array faster than np.sum?

#### 42. Consider two random array A and B, check if they are equal

#### 43. Make an array immutable (read-only) 

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

#### 45. Create random vector of size 10 and replace the maximum value by 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type

#### 49. How to print all the values of an array? 

#### 50. How to find the closest value (to a given scalar) in a vector?

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays?

#### 56. Generate a generic 2D Gaussian-like array

#### 57. How to randomly place p elements in a 2D array?

#### 58. Subtract the mean of each row of a matrix

#### 59. How to sort an array by the nth column?

#### 60. How to tell if a given 2D array has null columns?

#### 61. Find the nearest value from a given value in an array

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

#### 63. Create an array class that has a name attribute

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

#### 69. How to get the diagonal of a dot product?

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

#### 72. How to swap two rows of an array?

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

#### 75. How to compute averages using a sliding window over an array?

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

#### 77. How to negate a boolean, or to change the sign of a float inplace?

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 

#### 88. How to implement the Game of Life using numpy arrays?

#### 89. How to get the n largest values of an array

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 

#### 91. How to create a record array from a regular array?

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

#### 95. Convert a vector of ints into a matrix binary representation

#### 96. Given a two dimensional array, how to extract unique rows?

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).